image: Visual Studio 2019
branches:
  only:
    - master
clone_folder: c:\projects\gdl
configuration:
  - Release
  - Debug
environment:
  matrix:
  - platform: x86_64
  - platform: i686
   
matrix:
  fast_finish: true
  
init:
  - git config --global core.autocrlf input

install:
  - ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
  - ps: |
      C:\msys64\usr\bin\bash.exe -lc 'sed -i s/^CheckSpace/#CheckSpace/g /etc/pacman.conf && pacman --noconfirm -Syuu --overwrite *'
      C:\windows\system32\taskkill.exe /F /FI "MODULES eq msys-2.0.dll"
      C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -Suu --overwrite *'
  - ps: |	
      if ($env:platform -Match "i686") 	
      {	
        C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -S --needed --overwrite * git base-devel binutils mingw-w64-i686-toolchain'	
        $env:MSYSTEM="MINGW32" ; $env:mname="mingw32" ; $env:arch="i686"	
      }	
      elseif ($env:platform -Match "x86_64") 	
      {	
        C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -S --needed --overwrite * git base-devel binutils mingw-w64-x86_64-toolchain'	
        $env:MSYSTEM="MINGW64" ;  $env:mname="mingw64" ; $env:arch="x86_64"	
      }
  - ps: |
      cd c:/projects/gdl
      c:/msys64/usr/bin/bash.exe -lc 'cd $OLDPWD && ./.ci/build_gdl_windows.msys'

build_script:
  - ps: |
      cd c:/projects/gdl
      c:/msys64/usr/bin/bash.exe -lc 'cd $OLDPWD && ./.ci/build_gdl_windows.msys build'

on_failure:
  - ps: cat c:\projects\gdl\build\testsuite\Testing\Temporary\LastTest.log

after_build:
  - ps: c:\projects\gdl\.ci\ps1\test_gdl.ps1
  - ps: |
      copy C:\msys64\$env:mname\bin\*.dll install\bin\
      copy mingw\$env:mname\bin\*.dll install\bin\
      copy mingw\bsd-xdr-1.0.0\mingw\*.dll install\bin\
  - ps: |
      copy -r mingw\$env:mname\share\plplot* install\share\
      copy INSTALL.plplot install\
  - ps: copy -r src\pro install\pro\
  - 7z a gdl_build.zip install

artifacts:
  - path: gdl_build.zip
    name: GDL
  
deploy:
  release: gdl-master-build$(appveyor_build_version)
  description: 'Test release'
  provider: GitHub
  auth_token:
    secure: IhTPN2ggVb/gSjAnDAGleGO8+QQJETWjbuNtAvwQcJgEzKcZK944bMDIxSuLASgw
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
